PROS = [
    "Opportunity for personal growth",
    "Building a strong support system",
    "Shared financial responsibilities",
    "Emotional companionship",
    "Learning to compromise",
    "Creating lasting memories together",
    "Increased sense of security",
    "Opportunity to start a family",
    "Shared life goals and ambitions",
    "Celebrating milestones together",
    "Improved mental health through companionship",
    "Shared household responsibilities",
    "Strengthened social connections",
    "Mutual encouragement and motivation",
    "Financial stability through combined income",
    "Opportunity to travel and explore together",
    "Building a legacy together",
    "Learning new perspectives and ideas",
    "Increased happiness and life satisfaction",
    "Having someone to rely on during tough times",
    "Enhanced problem-solving through collaboration",
    "Opportunity to grow emotionally",
    "Shared hobbies and interests",
    "Support during career challenges",
    "Building a home together",
    "Creating a sense of belonging",
    "Shared celebrations and holidays",
    "Opportunity to learn from each other",
    "Strengthened resilience through partnership",
    "Shared dreams and aspirations",
    "Emotional stability through companionship",
    "Opportunity to create traditions",
    "Increased motivation to achieve goals",
    "Support during health challenges",
    "Opportunity to share responsibilities",
    "Building a future together",
    "Shared sense of purpose",
    "Opportunity to inspire each other",
    "Strengthened communication skills",
    "Opportunity to grow spiritually together",
    "Improved decision-making through collaboration",
    "Increased trust and understanding",
    "Opportunity to build a family legacy",
    "Shared experiences and adventures",
    "Mutual respect and admiration",
    "Opportunity to celebrate achievements together",
    "Increased emotional intelligence",
    "Opportunity to create a loving environment",
    "Support during challenging times",
    "Opportunity to learn patience and empathy",
    "Shared sense of humor and joy",
    "Opportunity to build a strong partnership",
    "Increased sense of belonging",
    "Opportunity to create a balanced life",
    "Shared values and principles",
    "Opportunity to grow together over time",
    "Increased sense of purpose",
    "Opportunity to build a meaningful life",
    "Shared commitment to personal growth",
    "Opportunity to create a supportive environment",
    "Increased sense of fulfillment",
    "Opportunity to build a strong foundation",
    "Shared sense of adventure",
    "Opportunity to create a positive impact",
    "Increased sense of connection",
    "Opportunity to build a lasting relationship",
    "Shared sense of responsibility",
    "Opportunity to create a harmonious life",
    "Increased sense of joy and happiness",
    "Opportunity to build a strong family",
    "Shared sense of achievement",
    "Opportunity to create a loving home",
    "Increased sense of trust and security",
    "Opportunity to build a meaningful partnership",
    "Shared sense of purpose and direction",
    "Opportunity to create a balanced partnership",
    "Increased sense of mutual respect",
    "Opportunity to build a strong bond",
    "Shared sense of belonging and connection",
    "Opportunity to create a positive environment",
    "Increased sense of shared goals",
    "Opportunity to build a strong relationship",
    "Shared sense of mutual support",
    "Opportunity to create a loving partnership",
    "Increased sense of shared values",
    "Opportunity to build a strong connection",
    "Shared sense of mutual understanding",
    "Opportunity to create a positive relationship",
    "Increased sense of shared purpose",
    "Opportunity to build a strong foundation for the future",
    "Shared sense of mutual trust",
    "Opportunity to create a harmonious partnership",
    "Increased sense of shared commitment",
    "Opportunity to build a strong and lasting relationship",
    "Shared sense of mutual growth",
    "Opportunity to create a positive and supportive environment",
    "Increased sense of shared happiness",
    "Opportunity to build a strong and loving family",
    "Opportunity to build a supportive community",
    "Chance to learn and grow through shared challenges",
]

CONS = [
    "Potential for conflicts and disagreements",
    "Loss of personal independence",
    "Financial strain from shared expenses",
    "Compromising on personal goals",
    "Increased responsibilities and obligations",
    "Risk of emotional vulnerability",
    "Potential for unmet expectations",
    "Balancing individual and shared priorities",
    "Time and energy investment required",
    "Adjusting to lifestyle changes",
    "Risk of relationship breakdown",
    "Managing differences in values or beliefs",
    "Potential for social or family pressures",
    "Loss of personal space and privacy",
    "Emotional toll during conflicts",
    "Financial risks in case of separation",
    "Sacrificing hobbies or interests",
    "Stress from shared decision-making",
    "Potential for unequal effort in the relationship",
    "Adapting to each other's habits and routines",
    "Risk of dependency on the partner",
    "Challenges in maintaining individuality",
    "Potential for jealousy or insecurity",
    "Difficulty in managing shared finances",
    "Risk of miscommunication",
    "Emotional strain during tough times",
    "Potential for differing life goals",
    "Balancing career and relationship demands",
    "Risk of burnout from shared responsibilities",
    "Challenges in maintaining work-life balance",
    "Potential for external judgment or criticism",
    "Risk of losing personal identity",
    "Difficulty in managing long-term conflicts",
    "Potential for resentment over sacrifices",
    "Challenges in maintaining romance over time",
    "Risk of emotional detachment",
    "Potential for unequal power dynamics",
    "Difficulty in managing extended family relationships",
    "Risk of stagnation in personal growth",
    "Challenges in maintaining mutual respect",
    "Potential for differing communication styles",
    "Risk of unmet emotional needs",
    "Challenges in balancing social commitments",
    "Potential for differing parenting styles",
    "Risk of financial disagreements",
    "Challenges in managing household responsibilities",
    "Potential for differing lifestyle preferences",
    "Risk of emotional exhaustion",
    "Challenges in maintaining physical intimacy",
    "Potential for differing career aspirations",
    "Risk of feeling unappreciated",
    "Challenges in managing health issues",
    "Potential for differing religious beliefs",
    "Risk of feeling unsupported",
    "Challenges in managing time together",
    "Potential for differing political views",
    "Risk of feeling neglected",
    "Challenges in managing stress",
    "Potential for differing cultural backgrounds",
    "Risk of feeling overwhelmed",
    "Challenges in managing expectations",
    "Potential for differing financial priorities",
    "Risk of feeling disconnected",
    "Challenges in managing personal boundaries",
    "Potential for differing social circles",
    "Risk of feeling isolated",
    "Challenges in managing shared goals",
    "Potential for differing travel preferences",
    "Risk of feeling misunderstood",
    "Challenges in managing shared interests",
    "Potential for differing dietary preferences",
    "Risk of feeling unfulfilled",
    "Challenges in managing shared values",
    "Potential for differing leisure activities",
    "Risk of feeling unsupported in personal growth",
    "Challenges in managing shared responsibilities",
    "Potential for differing work schedules",
    "Risk of feeling undervalued",
    "Challenges in managing shared commitments",
    "Potential for differing family dynamics",
    "Risk of feeling unimportant",
    "Challenges in managing shared traditions",
    "Potential for differing holiday preferences",
    "Risk of feeling unappreciated in the relationship",
    "Challenges in managing shared aspirations",
    "Potential for differing long-term goals",
    "Risk of feeling unrecognized",
    "Challenges in managing shared dreams",
    "Potential for differing short-term goals",
    "Risk of feeling unsupported in challenges",
    "Challenges in managing shared achievements",
    "Potential for differing definitions of success",
    "Risk of feeling unacknowledged",
    "Challenges in managing shared milestones",
    "Potential for differing expectations of the future",
    "Risk of feeling unimportant in the relationship",
    "Challenges in managing shared celebrations",
    "Potential for differing views on family planning",
    "Risk of feeling unappreciated in shared efforts",
    "Difficulty in balancing personal and professional life",
]
